on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: Convert username and repository name to lowercase
        run: |
          echo 'USER='$(echo $(dirname ${GITHUB_REPOSITORY}) | awk '{print tolower($0)}') >> $GITHUB_ENV
          echo 'REPO='$(echo $(basename ${GITHUB_REPOSITORY}) | awk '{print tolower($0)}') >> $GITHUB_ENV

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v2

      - name: 'Setup Docker buildx'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/arm64,linux/amd64
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.USER }}/${{ env.REPO }}:latest
  